<ul>
<li><label><input type="checkbox" name="rwapi-content-type[]" value="Analysis">Analysis</label></li>
<li><label><input type="checkbox" name="rwapi-content-type[]" value="Appeal">Appeal</label></li>
<li><label><input type="checkbox" name="rwapi-content-type[]" value="Assessment">Assessment</label></li>
<li><label><input type="checkbox" name="rwapi-content-type[]" value="Evaluation and Lessons Learned">Evaluation and Lessons Learned</label></li>
<li><label><input type="checkbox" name="rwapi-content-type[]" value="Infographic">Infographic</label></li>
<li><label><input type="checkbox" name="rwapi-content-type[]" value="Manual and Guideline">Manual and Guideline</label></li>
<li><label><input type="checkbox" name="rwapi-content-type[]" value="Map">Map</label></li>
<li><label><input type="checkbox" name="rwapi-content-type[]" value="News and Press Release">News and Press Release</label></li>
<li><label><input type="checkbox" name="rwapi-content-type[]" value="Situation Report">Situation Report</label></li>
<li><label><input type="checkbox" name="rwapi-content-type[]" value="UN Document">UN Document</label></li>
<li><label><input type="checkbox" name="rwapi-content-type[]" value="Other">Other</label></li>
</ul>