<ul>
<li><label><input type="checkbox" name="rwapi-language[]" value="English">English</label></li>
<li><label><input type="checkbox" name="rwapi-language[]" value="French">French</label></li>
<li><label><input type="checkbox" name="rwapi-language[]" value="Spanish">Spanish</label></li>
<li><label><input type="checkbox" name="rwapi-language[]" value="Arabic">Arabic</label></li>
<li><label><input type="checkbox" name="rwapi-language[]" value="Russian">Russian</label></li>
</ul>