<?php
// $Id: media_smugmug_image.module,v 1.3 2010/04/05 03:42:35 winston Exp $

/**
 *  @file
 *  Embedded Image Field provider file for Smugmug.com.
 */

function media_smugmug_image_emfield_providers($module, $provider = NULL) {
  if ($module == 'emimage') {
    return drupal_system_listing("smugmug_image\.inc", drupal_get_path('module', 'media_smugmug_image') ."/providers", 'name', 0);
  }
}
