<?php
$reliefweb_content_format = array(
	"Analysis" => "Analysis", 
	"Appeal" => "Appeal", 
	"Assessment" => "Assessment", 
	"Evaluation and Lessons Learned" => "Evaluation and Lessons Learned", 
	"Infographic" => "Infographic", 
	"Manual and Guideline" => "Manual and Guideline", 
	"Map" => "Map", 
	"News and Press Release" => "News and Press Release", 
	"Situation Report" => "Situation Report", 
	"UN Document" => "UN Document", 
	"Other" => "Other"
);
