<?php 
$reliefweb_organisation = array("Agence France-Presse" => "Agence France-Presse", 

"IRIN" => "IRIN", 

"UN Office for the Coordination of Humanitarian Affairs" => "UN Office for the Coordination of Humanitarian Affairs", 

"UN Resident and Humanitarian Coordinator in South Sudan" => "UN Resident and Humanitarian Coordinator in South Sudan",

"Reuters - AlertNet" => "Reuters - AlertNet", 

"IFRC" => "IFRC", 

"UN High Commissioner for Refugees" => "UN High Commissioner for Refugees", 

"UN News Service" => "UN News Service", 

"World Food Programme" => "World Food Programme", 

"UN Children's Fund" => "UN Children's Fund", 

"US Agency for International Development" => "US Agency for International Development", 

"World Health Organization" => "World Health Organization", 

"Xinhua" => "Xinhua", 

"UN Security Council" => "UN Security Council", 

"ICRC" => "ICRC", 

"Food and Agriculture Organization" => "Food and Agriculture Organization", 

"Famine Early Warning System Network" => "Famine Early Warning System Network", 

"Deutsche Presse Agentur" => "Deutsche Presse Agentur", 

"UN Department of Public Information" => "UN Department of Public Information", 

"Human Rights Watch" => "Human Rights Watch", 

"Radio Okapi" => "Radio Okapi", 

"US Department of State" => "US Department of State", 

"International Organization for Migration" => "International Organization for Migration", 

"World Bank" => "World Bank", 

"UN Secretary-General" => "UN Secretary-General", 

"Oxfam" => "Oxfam", 

"UN Development Programme" => "UN Development Programme", 

"Radio Free Europe / Radio Liberty" => "Radio Free Europe / Radio Liberty", 

"Government of the Philippines" => "Government of the Philippines", 

"European Union" => "European Union", 

"Voice of America" => "Voice of America", 

"Government of Colombia" => "Government of Colombia", 

"UN Organization Mission in the Democratic Republic of Congo" => "UN Organization Mission in the Democratic Republic of Congo", 

"Government of Angola" => "Government of Angola", 

"Amnesty" => "Amnesty", 

"Pan African News Agency" => "Pan African News Agency", 

"European Commission Humanitarian Aid department" => "European Commission Humanitarian Aid department", 

"UN General Assembly" => "UN General Assembly", 

"Action by Churches Together International" => "Action by Churches Together International", 

"World Vision" => "World Vision", 

"ReliefWeb" => "ReliefWeb", 

"Caritas" => "Caritas", 

"Save the Children" => "Save the Children", 

"CARE" => "CARE", 

"Institute for War and Peace Reporting" => "Institute for War and Peace Reporting", 

"UN Department of Humanitarian Affairs" => "UN Department of Humanitarian Affairs", 

"Government of Sri Lanka" => "Government of Sri Lanka", 

"Christian Science Monitor" => "Christian Science Monitor", 

"MSF" => "MSF", 

"Government of Japan" => "Government of Japan", 

"Church World Service" => "Church World Service", 

"Pan American Health Organization" => "Pan American Health Organization", 

"UN Assistance Mission in Afghanistan" => "UN Assistance Mission in Afghanistan", 

"Australian Broadcasting Corporation" => "Australian Broadcasting Corporation", 

"Government of Mexico" => "Government of Mexico", 

"UN Operation in Cote d'Ivoire" => "UN Operation in Cote d'Ivoire", 

"Refugees International" => "Refugees International", 

"UN Human Rights Council" => "UN Human Rights Council", 

"Government of Pakistan" => "Government of Pakistan", 

"UN Stabilization Mission in Haiti" => "UN Stabilization Mission in Haiti", 

"Department for International Development" => "Department for International Development", 

"Missionary International Service News Agency" => "Missionary International Service News Agency", 

"AlertNet" => "AlertNet", 

"UN Office of the High Commissioner for Human Rights" => "UN Office of the High Commissioner for Human Rights", 

"UN Relief and Works Agency for Palestine Refugees in the Near East" => "UN Relief and Works Agency for Palestine Refugees in the Near East", 

"Government of Guatemala" => "Government of Guatemala", 

"Government of the United States of America" => "Government of the United States of America", 

"North Atlantic Treaty Organisation" => "North Atlantic Treaty Organisation", 

"Government of Thailand" => "Government of Thailand", 

"Catholic Relief Services" => "Catholic Relief Services", 

"UN Radio" => "UN Radio", 

"International Crisis Group" => "International Crisis Group", 

"Government of Peru" => "Government of Peru", 

"Radio Dabanga" => "Radio Dabanga", 

"Mercy Corps" => "Mercy Corps", 

"AlterPresse" => "AlterPresse", 

"European Commission" => "European Commission", 

"Logistics Cluster" => "Logistics Cluster", 

"National Oceanic and Atmospheric Administration" => "National Oceanic and Atmospheric Administration", 

"Action Contre la Faim" => "Action Contre la Faim", 

"Palestinian Centre for Human Rights" => "Palestinian Centre for Human Rights", 

"UN Joint Logistics Centre" => "UN Joint Logistics Centre", 

"Agency for Technical Cooperation and Development" => "Agency for Technical Cooperation and Development", 

"UN Interim Administration Mission in Kosovo" => "UN Interim Administration Mission in Kosovo", 

"Government of India" => "Government of India", 

"Government of Ecuador" => "Government of Ecuador", 

"Government of Bolivia" => "Government of Bolivia", 

"Miraya FM" => "Miraya FM", 

"UNOSAT" => "UNOSAT", 

"Government of Kenya" => "Government of Kenya", 

"Sudan Tribune" => "Sudan Tribune", 

"Adventist Development and Relief Agency International" => "Adventist Development and Relief Agency International", 

"Government of France" => "Government of France", 

"Christian Aid" => "Christian Aid", 

"PlusNews" => "PlusNews", 

"DAWN Group of Newspapers" => "DAWN Group of Newspapers", 

"UN Mission in Sudan" => "UN Mission in Sudan", 

"Government of Australia" => "Government of Australia", 

"MapAction" => "MapAction", 

"International Medical Corps" => "International Medical Corps", 

"International Rescue Committee" => "International Rescue Committee", 

"UN-AU Mission in Darfur" => "UN-AU Mission in Darfur", 

"ZimOnline" => "ZimOnline", 

"UN Mission in Liberia" => "UN Mission in Liberia", 

"African Union" => "African Union", 

"Organization for Security and Co-operation in Europe" => "Organization for Security and Co-operation in Europe", 

"Inter Press Service" => "Inter Press Service", 

"Australian Agency for International Development" => "Australian Agency for International Development", 

"Jesuit Refugee Service" => "Jesuit Refugee Service", 

"Irrawaddy" => "Irrawaddy", 

"ActionAid" => "ActionAid", 

"Jakarta Post" => "Jakarta Post", 

"Council of Europe" => "Council of Europe", 

"United Methodist Committee on Relief" => "United Methodist Committee on Relief", 

"Canadian International Development Agency" => "Canadian International Development Agency", 

"Government of the People's Republic of China" => "Government of the People's Republic of China", 

"Government of Israel" => "Government of Israel", 

"Government of Viet Nam" => "Government of Viet Nam", 

"Government of Afghanistan" => "Government of Afghanistan", 

"Government of Ethiopia" => "Government of Ethiopia", 

"Government of Germany" => "Government of Germany", 

"American Red Cross" => "American Red Cross", 

"UN Transitional Administration in East Timor" => "UN Transitional Administration in East Timor", 

"Plan" => "Plan", 

"UN Population Fund" => "UN Population Fund", 

"Government of Canada" => "Government of Canada", 

"UN Mission in Ethiopia and Eritrea" => "UN Mission in Ethiopia and Eritrea", 

"Guardian" => "Guardian", 

"Government of Eritrea" => "Government of Eritrea", 

"Times of India" => "Times of India", 

"Government of Venezuela" => "Government of Venezuela", 

"Concern Worldwide" => "Concern Worldwide", 

"ACT Alliance" => "ACT Alliance", 

"British Red Cross" => "British Red Cross", 

"UN Assistance Mission for Iraq" => "UN Assistance Mission for Iraq", 

"Sudanese News Agency" => "Sudanese News Agency", 

"Government of Chile" => "Government of Chile", 

"Asian Development Bank" => "Asian Development Bank", 

"Mennonite Central Committee" => "Mennonite Central Committee", 

"UN Mission in Sierra Leone" => "UN Mission in Sierra Leone", 

"Direct Relief" => "Direct Relief", 

"Le Potentiel" => "Le Potentiel", 

"Government of the United Kingdom" => "Government of the United Kingdom", 

"Catholic Agency for Overseas Development" => "Catholic Agency for Overseas Development", 

"UN International Strategy for Disaster Reduction" => "UN International Strategy for Disaster Reduction", 

"Internal Displacement Monitoring Centre" => "Internal Displacement Monitoring Centre", 

"Mines Advisory Group" => "Mines Advisory Group", 

"Swiss Agency for Development and Cooperation" => "Swiss Agency for Development and Cooperation", 

"UN Environment Programme" => "UN Environment Programme", 

"Mizzima News" => "Mizzima News", 

"Palestine Red Crescent Society" => "Palestine Red Crescent Society", 

"United Nations Association of Georgia" => "United Nations Association of Georgia", 

"El Espectador" => "El Espectador", 

"Government of the Russian Federation" => "Government of the Russian Federation", 

"Government of Honduras" => "Government of Honduras", 

"Prague Watchdog" => "Prague Watchdog", 

"Radio Kiskeya" => "Radio Kiskeya", 

"Handicap International" => "Handicap International", 

"Emirates News Agency" => "Emirates News Agency", 

"Government of the Dominican Republic" => "Government of the Dominican Republic", 

"Federal Emergency Management Agency" => "Federal Emergency Management Agency", 

"African Development Bank" => "African Development Bank", 

"Norwegian Refugee Council" => "Norwegian Refugee Council", 

"Tearfund" => "Tearfund", 

"Government of Fiji" => "Government of Fiji", 

"Islamic Relief" => "Islamic Relief", 

"UN Organization Stabilization Mission in the Democratic Republic of the Congo" => "UN Organization Stabilization Mission in the Democratic Republic of the Congo", 

"Trucaire" => "Trucaire", 

"AmeriCares" => "AmeriCares", 

"Yemen Times" => "Yemen Times", 

"Government of Italy" => "Government of Italy", 

"Government of Serbia" => "Government of Serbia", 

"UN Country Team in Sudan" => "UN Country Team in Sudan", 

"Cruz Roja Espanola" => "Cruz Roja Espanola", 

"Government of Bangladesh" => "Government of Bangladesh", 

"Medecins du Monde" => "Medecins du Monde", 

"Government of Myanmar" => "Government of Myanmar", 

"Government of Cuba" => "Government of Cuba", 

"Lutheran World Relief" => "Lutheran World Relief", 

"Government of Norway" => "Government of Norway", 

"International Monetary Fund" => "International Monetary Fund", 

"United Nations" => "United Nations", 

"US Information Agency" => "US Information Agency", 

"Inter-American Development Bank" => "Inter-American Development Bank", 

"US Geological Survey" => "US Geological Survey", 

"Kuwait News Agency" => "Kuwait News Agency", 

"International Criminal Court" => "International Criminal Court", 

"Al Mezan Center for Human Rights" => "Al Mezan Center for Human Rights", 

"Government of Sweden" => "Government of Sweden", 

"Kenya Red Cross" => "Kenya Red Cross", 

"InterAction" => "InterAction", 

"Fondation Hirondelle" => "Fondation Hirondelle", 

"Good Friends: Centre for Peace, Human Rights and Refugees" => "Good Friends: Centre for Peace, Human Rights and Refugees", 

"Myanmar Information Management Unit" => "Myanmar Information Management Unit", 

"EurasiaNet" => "EurasiaNet", 

"Government of the Republic of Mali" => "Government of the Republic of Mali", 

"Mail and Guardian" => "Mail and Guardian", 

"International Charter" => "International Charter", 

"US Institute of Peace" => "US Institute of Peace", 

"Government of New Zealand" => "Government of New Zealand", 

"US Committee for Refugees and Immigrants" => "US Committee for Refugees and Immigrants");
