<?php
$reliefweb_theme = array("Agriculture" => "Agriculture", 

"Climate Change and Environment" => "Climate Change and Environment", 

"Contributions" => "Contributions", 

"Coordination" => "Coordination", 

"Disaster Management" => "Disaster Management", 

"Education" => "Education", 

"Food and Nutrition" => "Food and Nutrition", 

"Gender" => "Gender", 

"Health" => "Health", 

"HIV/Aids" => "HIV/Aids", 

"Humanitarian Financing" => "Humanitarian Financing", 

"Logistics and Telecommunications" => "Logistics and Telecommunications", 

"Mine Action" => "Mine Action", 

"Other" => "Other", 

"Peacekeeping and Peacebuilding" => "Peacekeeping and Peacebuilding", 

"Protection and Human Rights" => "Protection and Human Rights", 

"Recovery and Reconstruction" => "Recovery and Reconstruction", 

"Safety and Security" => "Safety and Security", 

"Shelter and Non-Food Items" => "Shelter and Non-Food Items", 

"Water Sanitation Hygiene" => "Water Sanitation Hygiene"
);