<?php
/**
 * Implementation of hook_menu
 */
function reliefwebpanel_menu() {
  $items = array();

  $items["admin/settings/reliefweb/panel"] = array(
      'title' => 'Ctools Plugin Example',
      'description' => t("Relief Web Panel page."),
      'page callback' => 'reliefwebpanel_explanation_page',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Implementation of hook_ctools_plugin_directory().
 * It simply tells panels where to find the .inc files that define various args, contexts, content_types
 * In this case the subdirectories of ctools_plugin_example/panels are used
 */
function reliefwebpanel_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implement hook_ctools_plugin_api().
 * If you do this, Ctools will pick up default panels pages in
 * <modulename>.pages_default.inc
 */
function reliefwebpanel_ctools_plugin_api($module, $api) {
  if ($module == 'panels_mini' && $api == 'panels_default') {
    return array('version' => 1);
  }
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Just provide an explanation page for the admin section
 * @return unknown_type
 */
function reliefwebpanel_explanation_page() {
  $demo_panel = l("ReliefWeb API Panel",'reliefwebpanel/xxxxx');
  $ctools_help = theme('advanced_help_topic', 'ctools', 'plugins', 'title');
  $ctools_plugin_example_help = theme('advanced_help_topic','ctools_plugin_example','Chaos-Tools--Ctools--Plugin-Examples','title');
  $path = drupal_get_path('module','ctools_plugin_example');
  $content .= <<<END
  <p>The Ctools Plugin Example is simply a developer's demo of how to create plugins for Ctools.
  It provides no useful functionality for an ordinary user.
  </p>
  <p>There is a demo panel demonstrating much of the functionality provided at
  $demo_panel, and you can find documentation on the examples at $ctools_plugin_example_help.
  Ctools itself provides documentation at $ctools_help. Mostly, though, the code itself
  is intended to be the teacher. You can find it at <i>$path</i>.</p>

END;
  return $content;

}